### ISSUE TITLE
Intel Edison Network Manager support

### ISSUE THREAD

**Issue by egorf** [balena-os/balena-edison#107]
Hello @floion,

I have a question regarding the NetworkManager support in Edison by Resin team. I'm looking for a way to move the whole Wi-Fi stack to NM in my Edison image. Everything seems to work good, except for the need to reload the `bcm4334x` kernel module when switching between Client and Master modes.

I have seen that resin-wifi-connect has code to specifically do this for the Edison. Do you think it is possible to avoid that and move this responsibility to the NM? Did you guys have any success working around this limitation?

Thanks!

**Comment by floion** [comment]
Hi,
and sorry for the late response.
I haven't looked into this myself, let's ask @majorz as he handles the resin-wifi-connect project

**Comment by shaunmulligan** [comment]
@egorf and @floion from my testing on our latest edison image with the 4.13 kernel, the intel edison specific code in wifi-connect is not needed, it all just works the same as RPI3

**Comment by egorf** [comment]
@shaunmulligan How stable was the recent kernel on Edison? I am also really interested in the scale you've tried to use it in

**Comment by floion** [comment]
Since we made the move to kernel 4.x we did not find stability issues with it.
Neither did our customers report any issues
