### ISSUE TITLE
error: no matching package named `atty` found (required by `cargo`)

### ISSUE THREAD

**Issue by paroque28** [balena-os/balena-edison#139]
Look at https://github.com/meta-rust/meta-rust/issues/224

DEBUG: Executing shell function do_compile
NOTE: cargo = /wr/sandbox/prodrigu/cases/balenaOS/balena-edison/build/tmp/work/x86_64-linux/cargo-native/0.25.0-r0/cargo-0.24.0-x86_64-unknown-linux-gnu/cargo/bin/cargo
NOTE: rustc =
NOTE: /wr/sandbox/prodrigu/cases/balenaOS/balena-edison/build/tmp/work/x86_64-linux/cargo-native/0.25.0-r0/cargo-0.24.0-x86_64-unknown-linux-gnu/cargo/bin/cargo build -v --target x86_64-linux --release
error: no matching package named atty found (required by cargo)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: = 0.2.11
WARNING: /wr/sandbox/prodrigu/cases/balenaOS/balena-edison/build/tmp/work/x86_64-linux/cargo-native/0.25.0-r0/temp/run.do_compile.141829:1 exit 101 from '"/wr/sandbox/prodrigu/cases/balenaOS/balena-edison/ build/tmp/work/x86_64-linux/cargo-native/0.25.0-r0/cargo-0.24.0-x86_64-unknown-linux-gnu/cargo/bin/cargo" build -v --target x86_64-linux --release "$@"'
ERROR: Function failed: do_compile (log file is located at /wr/sandbox/prodrigu/cases/balenaOS/balena-edison/build/tmp/work/x86_64-linux/cargo-native/0.25.0-r0/temp/log.do_compile.141829)

**Comment by siredmar** [comment]
I have the exact same problem building balenaOs for raspberry Pi.

**Comment by floion** [comment]
@paroque28 did you eventually make it go past this problem? Or is it still an issue for you?
Are you seeing this in a new build or on an existing incremental build?

**Comment by floion** [comment]
This was fixed for @siredmar by using an OS distro and version supported by Poky. So considering this and the lack of reply, will close this issue here
